---
- name: install docker, jenkins, letsencrypt on ubuntu
  hosts: dockerhosts
  # remote_user: "{{ remote_user }}"
  remote_user: root
  #  become: yes
  # become_method: sudo
  # become_user: root

  tasks:
    # Jenkins
    - name: install jenkins key
      raw: wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
    - name: copy jenkins.list to sources.list.d
      template:
        src: jenkins.list
        dest: /etc/apt/sources.list.d/jenkins.list
    # Docker
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    # Update packages
    - name: update packages
      apt: update_cache=yes # force_apt_get=yes cache_valid_time=3600
    # Upgrade packages
    - name: upgrade all packages
      apt: upgrade=dist # force_apt_get=yes
    # Install required packages
    - name: install required system packages
      apt: name={{ item }} state=latest update_cache=yes #force_apt_get=yes
      loop:
        [
          "apt-transport-https",
          "ca-certificates",
          "curl",
          "software-properties-common",
          "python3-pip",
          "virtualenv",
          "python3-setuptools",
          "python-simplejson",
          "letsencrypt",
          "certbot",
          "nginx",
          "python3",
          "python3-certbot",
          "python-certbot-doc",
          "python3-certbot-nginx",
          "python3-venv",
          "openjdk-8-jdk",
          "wget",
          "jenkins",
          "docker-ce",
        ]

    - name: create docker group
      group: name=docker state=present

    # - name: user 'phan' join docker group
    #   user:
    #     name: phan
    #     groups: admin,docker
    # This repo does not support ubuntu 20.x currently
    # - name: add certbot repository
    #   apt_repository:
    #     repo: ppa:certbot/certbot
    #     state: present
    #     update_cache: yes
    #     validate_certs: False

    - name: install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.25.1/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: "u+x,g+x"

    - name: test docker
      raw: docker run --rm hello-world

    - name: remove hello-world image from docker
      raw: docker rmi hello-world

    - name: user 'jenkins' join docker group
      user:
        name: jenkins
        groups: docker

    # Jenkins
    - name: restart jenkins for new config
      service:
        name: jenkins
        state: restarted

    # config letsencrypt + nginx
    - name: create letsencrypt directory
      file:
        name: /var/www/letsencrypt
        state: directory

    - name: Remove default nginx config
      file:
        name: /etc/nginx/sites-enabled/default
        state: absent

    - name: Install system nginx config
      template:
        src: nginx-conf.j2
        dest: /etc/nginx/nginx.conf

    - name: Install default site for letsencrypt process
      template:
        src: nginx-http-pre.j2
        dest: /etc/nginx/sites-enabled/default

    - name: Reload nginx config
      service: name=nginx state=restarted

    - name: Create letsencrypt certificate for ssl_domains {{ item }}
      shell: letsencrypt certonly -n --webroot -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos -d {{ item }}
      args:
        creates: /etc/letsencrypt/live/{{ item }}
      loop: "{{ ssl_domains|flatten }}"

    - name: Generate dhparams
      shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
      args:
        creates: /etc/nginx/dhparams.pem

    - name: Copy config - nginx sites for ssl_domains (http) - {{ item }}
      template:
        src: "{{ item }}-http.j2"
        dest: "/etc/nginx/sites-enabled/{{ item }}-http"
      loop: "{{ ssl_domains|flatten }}"

    - name: Copy config - nginx sites for ssl_domains (https) - {{ item }}
      template:
        src: "{{ item }}-https.j2"
        dest: "/etc/nginx/sites-enabled/{{ item }}-https"
      loop: "{{ ssl_domains|flatten }}"

    - name: Reload nginx to activate specified site
      service: name=nginx state=restarted

    - name: Add letsencrypt cronjob for cert renewal
      cron:
        name: letsencrypt_renewal
        special_time: weekly
        job: letsencrypt --renew certonly -n --webroot -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos {{ (['-d '] * ssl_domains|length)|zip(ssl_domains)|map('join')|join(' ')  }} && service nginx reload

    - name: Reading default jenkins default password
      command: "cat /var/lib/jenkins/secrets/initialAdminPassword"
      register: jenkins_default_password
      ignore_errors: True
    - name: Display jenkins default password
      debug:
        msg: "{{jenkins_default_password.stdout}}"
      ignore_errors: True
    - name: test display
      debug:
        # msg: "{{ ssl_domains | map('regex_replace', '(.*)', '-d \\1') | map('join') }}"
        msg: "{{ (['-d '] * ssl_domains|length)|zip(ssl_domains)|map('join')|join(' ')  }}"
    - name: Restart server
      reboot:
        reboot_timeout: 3600
    # - name: with_flattened -> loop
    #   debug:
    #     msg: "{{ item }}"
    #   loop: "{{ ssl_domains|flatten }}"
